### ISSUE TITLE
Map WooCommerce checkout fields to subscribers

### ISSUE THREAD

**Issue by Maria-tribulant** [TribulantSoftware/newsletters-woocommerce#10]
Specific request was for First Name and Last Name to be captured.

**Comment by tribulant** [comment]
Added settings for this under Newsletters > Extensions > Settings > WooCommerce Subscribers.
![2019-07-26_01-27-14](https://user-images.githubusercontent.com/706531/61915411-8ffefb00-af44-11e9-9a02-c1ed93d6e56b.png)
